_commit: v1.3.0-3-gea55d96
_src_path: https://github.com/ff-fab/tmpl_python_project_kickstart
author_email: mail@fabiankoerner.com
author_name: Fabian Koerner
codecov: true
coverage_threshold: 80
description: A smart home app to control a Vitodens gas heating.
docs_style: user-journey
github_org: ff-fab
init_git_on_copy: true
license: MIT
module_name: vito2mqtt
project_name: vito2mqtt
release_please: true
repo_name: vito2mqtt
robot_framework: false
